/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package legendary.octo.sniffle.app;

import com.google.inject.Guice;

import legendary.octo.sniffle.cli.CommandDispatcher;
import picocli.CommandLine;

public class App {
    public String getGreeting() {
        return "Hello world Test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        var injector = Guice.createInjector(new AppModule());
        new CommandLine(injector.getInstance(CommandDispatcher.class)).execute(args);
    }
}
